Repository my-balance-one-trillion/janack-overflow, pull requests merged in 2023-12, with the labels that each got.

#32 Feature/4 백엔드 에러페이지
  janack-overflow/.gitignore
  janack-overflow/src/main/generated/com/example/janackoverflow/saving/entity/QInputAccount.java
  janack-overflow/src/main/generated/com/example/janackoverflow/saving/entity/QRule.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/ExceptionCode.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/security/SecurityConfig.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/controller/IssueController.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/controller/SavingController.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/request/RuleRequestDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/request/SavingRequestDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/request/UpdateAccountStatusRequestDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/entity/InputAccount.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/entity/Rule.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/repository/RuleRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/service/InputAccountService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/service/RuleService.java
Labels: backend

#36 Feature/28 프론트 커뮤니티페이지
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.vue
  client/src/assets/css/common.css
  client/src/components/Header.vue
  client/src/main.js
  client/src/pages/Community.vue
  client/src/pages/CommunityDetail.vue
  client/src/router/index.js
  client/tailwind.config.js
  client/vite.config.js
  janack-overflow/src/main/generated/com/example/janackoverflow/saving/entity/QInputAccount.java
  janack-overflow/src/main/generated/com/example/janackoverflow/saving/entity/QRule.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/domain/CommentDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/domain/MediumArticle.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/repository/LikesRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommentService.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/LikesService.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/config/WebConfig.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/domain/IssueDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/domain/SolutionDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/entity/Issue.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/entity/Solution.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/SolutionRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/SolutionService.java
Labels: backend, frontend

#37 Feature/34 프론트 적금페이지
  client/cssrun.sh
  client/package-lock.json
  client/package.json
  client/public/images/congrats.svg
  client/public/images/emojiSad.svg
  client/public/images/logo.svg
  client/src/components/Saving/Details/MonthlyDetails.vue
  client/src/components/Saving/Details/MyAccount.vue
  client/src/components/Saving/Intro.vue
  client/src/components/Saving/OpenAccount.vue
  client/src/components/Saving/OpenAccountFinish.vue
  client/src/components/Saving/SavingDelete.vue
  client/src/components/Saving/SavingDetails.vue
  client/src/components/Saving/SavingEdit.vue
  client/src/components/Saving/SavingRecord.vue
  client/src/components/Saving/SavingSideBar.vue
  client/src/components/Saving/component/DoughnutChart.vue
  client/src/components/Saving/component/HorizontalBarChart.vue
  client/src/components/Saving/component/LineChart.vue
  client/src/components/Saving/component/ProgressBar.vue
  client/src/pages/Saving.vue
  client/src/router/index.js
  janack-overflow/.gitignore
  janack-overflow/src/main/java/com/example/janackoverflow/issue/domain/response/IssueResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/IssueRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/controller/SavingController.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/response/InputAccountResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/response/RuleResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/response/SavingResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/entity/InputAccount.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/repository/RuleRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/service/InputAccountService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/service/RuleService.java
  package-lock.json
Labels: frontend

#38 Feature/29 프론트 메인페이지
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/images/main-coin.gif
  client/public/images/mainImg1.png
  client/src/App.vue
  client/src/components/Chart.vue
  client/src/components/chat/ChatList.vue
  client/src/components/main/IssueTable.vue
  client/src/components/main/LoggedInMain.vue
  client/src/components/main/LoggedOutMain.vue
  client/src/components/main/MainPageCard.vue
  client/src/main.js
  client/src/pages/Main.vue
  client/src/pages/chat/Chat.vue
  client/src/pages/chat/ChatMain.vue
  client/src/pages/chat/MyChat.vue
  client/src/router/index.js
  client/tailwind.config.js
  janack-overflow/.gitignore
  janack-overflow/src/main/generated/com/example/janackoverflow/chat/entity/QChatMessage.java
  janack-overflow/src/main/generated/com/example/janackoverflow/chat/entity/QChatRoom.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/config/WebSocketConfig.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatRoomController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/SocketController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/domain/ChatMessageDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/domain/ChatRoomDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/entity/ChatMessage.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/entity/ChatRoom.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/repository/ChatMessageRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/repository/ChatRoomRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/service/ChatMessageService.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/service/ChatRoomService.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/security/SecurityConfig.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/domain/response/IssueResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/IssueRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/main/controller/MainController.java
  janack-overflow/src/main/java/com/example/janackoverflow/main/domain/NowAccountResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/main/service/BankingService.java
  janack-overflow/src/main/java/com/example/janackoverflow/main/service/MainService.java
  janack-overflow/src/test/java/com/example/janackoverflow/JanackOverflowApplicationTests.java
Labels: backend, frontend

#41 Feature/28 프론트 커뮤니티페이지
  client/index.html
  client/src/App.vue
  client/src/pages/Community.vue
  client/src/pages/CommunityDetail.vue
  client/src/pages/Login.vue
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/repository/CommentListRepositoruImpl.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/repository/CommentListRespository.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/repository/CommunityRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/repository/CommunityRepositoryImpl.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommentService.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/entity/Issue.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/entity/Solution.java
Labels: backend, frontend

#49 Feature/34 프론트 적금페이지
  client/package-lock.json
  client/package.json
  client/src/components/Issue/AboutIssue.vue
  client/src/components/Issue/IssueModal.vue
  client/src/components/Issue/Solving.vue
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Issue/SubmitSolution.vue
  client/src/components/Saving/Details/MonthlyDetails.vue
  client/src/pages/Issue.vue
  client/src/pages/Saving.vue
  janack-overflow/src/main/java/com/example/janackoverflow/issue/controller/IssueController.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/domain/response/SolutionResponseDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/IssueRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/SolutionRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/SolutionService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/controller/SavingController.java
Labels: frontend

#50 Feature/28 프론트 커뮤니티페이지
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/components/Dropdown.vue
  client/src/main.js
  client/src/pages/CommunityDetail.vue
  client/tailwind.config.js
Labels: frontend

#54 feat: #34 월별 적금 내역, 적금 횟수 구현
  client/src/components/Saving/Details/HorizontalBarChart.vue
  client/src/components/Saving/Details/LineChart.vue
  client/src/components/Saving/SavingDetails.vue
  client/src/components/Saving/component/HorizontalBarChart.vue
  client/src/components/Saving/component/LineChart.vue
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/IssueRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/SolutionRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/SolutionService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/controller/SavingController.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/response/MonthlyAmountDTO.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/domain/response/MonthlyCountIssueDTO.java
Labels: frontend

#56 Feature/28 프론트 커뮤니티페이지
  client/src/components/Dropdown.vue
  client/src/components/Spinner.vue
  client/src/pages/CommunityDetail.vue
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommentService.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/entity/Issue.java
Labels: backend, frontend

#57 feat: #34 월별 적금 횟수, 금액 차트 구현
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Saving/Details/Chart.vue
  client/src/components/Saving/Details/HorizontalBarChart.vue
  client/src/components/Saving/Details/LineChart.vue
  client/src/components/Saving/SavingDetails.vue
  client/src/components/Saving/component/DoughnutChart.vue
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
Labels: frontend

#59 Feature/34 프론트 적금페이지
  client/package-lock.json
  client/package.json
  client/src/components/Issue/AboutIssue.vue
  client/src/components/Issue/CodeEditor.vue
  client/src/components/Issue/Solving.vue
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Issue/SubmitSolution.vue
  client/src/components/Saving/Details/Chart.vue
  client/src/components/Saving/SavingDetails.vue
  client/src/pages/CommunityDetail.vue
  client/src/pages/Issue.vue
  client/yarn.lock
Labels: frontend

#60 Feature/29 프론트 메인페이지
  client/package.json
  client/src/components/Chart.vue
  client/src/components/chat/ChatCreateModal.vue
  client/src/components/chat/ChatList.vue
  client/src/components/main/IssueTable.vue
  client/src/components/main/LoggedInMain.vue
  client/src/components/main/LoggedOutMain.vue
  client/src/main.js
  client/src/pages/AboutGivenUpIssue.vue
  client/src/pages/Login.vue
  client/src/pages/Mypage.vue
  client/src/pages/chat/ChatMain.vue
  client/src/pages/chat/ChatRoom.vue
  client/src/router/index.js
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatRoomController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/repository/ChatRoomRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/service/ChatRoomService.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/config/WebConfig.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/IssueRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/main/service/MainService.java
Labels: backend

#64 Feature/28 프론트 커뮤니티페이지
  client/package-lock.json
  client/package.json
  client/src/components/Dropdown.vue
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Monaco.vue
  client/src/pages/CommunityDetail.vue
  client/yarn.lock
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
Labels: backend, frontend

#66 Feature/28 프론트 커뮤니티페이지
  client/package-lock.json
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Saving/Details/MonthlyDetails.vue
  client/src/pages/CommunityDetail.vue
  client/yarn.lock
Labels: backend

#69 Feature/28 프론트 커뮤니티페이지
  client/src/components/main/MainPageCard.vue
  client/src/main.js
  client/src/pages/CommunityDetail.vue
  client/src/pages/Login.vue
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
Labels: backend, frontend

#70 feat: #29 채팅방 정렬, 채팅 표시 수정
  client/public/images/main-text.svg
  client/src/components/Chart.vue
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/chat/ChatList.vue
  client/src/components/main/IssueTable.vue
  client/src/components/main/LoggedInMain.vue
  client/src/components/main/LoggedOutMain.vue
  client/src/components/main/MainPageCard.vue
  client/src/pages/AboutGivenUpIssue.vue
  client/src/pages/chat/ChatRoom.vue
  client/yarn.lock
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatMessageController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatRoomController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/repository/ChatMessageRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/service/ChatMessageService.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/service/ChatRoomService.java
  janack-overflow/src/test/java/com/example/janackoverflow/JanackOverflowApplicationTests.java
Labels: frontend

#72 Feature/34 프론트 적금페이지
  client/package.json
  client/src/components/Issue/AboutIssue.vue
  client/src/components/Issue/IssueModal.vue
  client/src/components/Issue/Solving.vue
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Issue/SubmitSolution.vue
  client/src/components/Saving/Details/Chart.vue
  client/src/components/Saving/Details/MyAccount.vue
  client/src/components/Saving/Intro.vue
  client/src/components/Saving/OpenAccount.vue
  client/src/components/Saving/OpenAccountFinish.vue
  client/src/components/Saving/SavingDelete.vue
  client/src/components/Saving/SavingDetails.vue
  client/src/components/Saving/SavingSideBar.vue
  client/src/pages/Issue.vue
  janack-overflow/src/main/java/com/example/janackoverflow/saving/controller/SavingController.java
Labels: frontend

#75 Feature/28 프론트 커뮤니티페이지
  client/src/components/Footer.vue
  client/src/main.js
  client/src/pages/Community.vue
  client/src/pages/CommunityDetail.vue
  client/src/pages/SignUp.vue
  janack-overflow/src/main/java/com/example/janackoverflow/community/controller/CommunityController.java
  janack-overflow/src/main/java/com/example/janackoverflow/community/service/CommunityService.java
Labels: backend, frontend

#76 fix: #34 css 수정
  client/src/components/Issue/AboutIssue.vue
  client/src/components/Saving/Details/MonthlyDetails.vue
  client/src/components/Saving/SavingDetails.vue
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
Labels: frontend

#77 feat: #29 메인 페이지 수정
  client/src/components/Header.vue
  client/src/components/main/IssueTable.vue
  client/src/components/main/LoggedInMain.vue
  client/src/components/main/LoggedOutMain.vue
  client/src/components/main/MainPageCard.vue
  client/src/pages/Main.vue
  janack-overflow/src/main/java/com/example/janackoverflow/chat/ClientWebSocketStompSessionHandler.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/config/ClientWebSocketStompConfig.java
Labels: frontend

#79 fix: #34 css 수정
  client/src/components/Issue/SubmitIssue.vue
  client/src/components/Saving/Details/MyAccount.vue
  client/src/components/Saving/SavingDetails.vue
Labels: frontend

#84 feat: #29 전체 css 수정 및 기능 오류 수정
  client/src/components/chat/ChatCreateModal.vue
  client/src/components/chat/ChatList.vue
  client/src/components/main/LoggedInMain.vue
  client/src/components/main/LoggedOutMain.vue
  client/src/components/main/MainPageCard.vue
  client/src/main.js
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatMessageController.java
  janack-overflow/src/main/java/com/example/janackoverflow/chat/controller/ChatRoomController.java
  janack-overflow/src/test/java/com/example/janackoverflow/JanackOverflowApplicationTests.java
Labels: frontend

#86 Feature/29 프론트 메인페이지
  client/src/components/main/LoggedInMain.vue
  client/src/components/main/LoggedOutMain.vue
  client/src/main.js
  client/src/pages/Main.vue
  janack-overflow/src/main/java/com/example/janackoverflow/issue/entity/Issue.java
  janack-overflow/src/test/java/com/example/janackoverflow/JanackOverflowApplicationTests.java
Labels: frontend

#89 feat: #5 예외처리 exception code 및 custom exception 추가
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/BusinessLogicException.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/ExceptionCode.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/GlobalExceptionHandler.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/StatusResponse.java
Labels: backend

#90 feat: #5 공통 exception code 수정
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/BusinessLogicException.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/StatusResponse.java
Labels: backend

#92 Feature/34 프론트 적금페이지
  client/src/pages/Error.vue
  client/src/pages/Issue.vue
  client/src/router/index.js
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/ExceptionCode.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/controller/IssueController.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/IssueRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/repository/SolutionRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/issue/service/IssueService.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/controller/SavingController.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/repository/InputAccountRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/repository/RuleRepository.java
  janack-overflow/src/main/java/com/example/janackoverflow/saving/service/InputAccountService.java
Labels: backend, frontend

#93 chore: #30 예외처리, 프론트 일부수정
  client/src/components/mypage/dashboard.vue
  client/src/components/mypage/mycomment.vue
  client/src/components/mypage/myissue.vue
  client/src/pages/Mypage.vue
  janack-overflow/src/main/java/com/example/janackoverflow/admin/service/AdminService.java
  janack-overflow/src/main/java/com/example/janackoverflow/global/exception/ExceptionCode.java
  janack-overflow/src/main/java/com/example/janackoverflow/mypage/service/MypageService.java
  janack-overflow/src/main/java/com/example/janackoverflow/user/service/UsersService.java
Labels: fix

#94 chore: header수정
  client/src/assets/css/common.css
  client/src/components/Header.vue
Labels: fix

#95 chore: #30 헤더 추가수정
  client/src/components/Header.vue
Labels: fix

#98 chore: #30 회원정보수정 오류해결, 프론트 오류수정
  client/index.html
  client/src/components/Header.vue
  client/src/main.js
  client/src/pages/Admin.vue
  janack-overflow/src/main/java/com/example/janackoverflow/mypage/service/MypageService.java
Labels: fix

#99 chore: #30 모달 일부적용
  client/src/App.vue
  client/src/assets/css/common.css
  client/src/components/Header.vue
  client/src/components/Modal.vue
Labels: fix
